# UI-container
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ui-container
  name: ui-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ui-container
    spec:
      containers:
        - name: ui-container
          image: cogitoparadigm/assignment06-ui:test
          imagePullPolicy: Always
status: {}
---
# Service
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ui-container-service
  name: ui-container-service
spec:
  type: NodePort
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ui-container
status:
  loadBalancer: {}
